# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@devcontainers/cli-0.55.0" = {
      name = "_at_devcontainers_slash_cli";
      packageName = "@devcontainers/cli";
      version = "0.55.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@devcontainers/cli/-/cli-0.55.0.tgz";
        sha512 = "U7wCt82wT3kB88dNCibUZiMfS8fw5T3iXHhqnss7d0oJsU5H42RwU4VgiT/Gx+xr+bGTReDWvw/zudsynyHozQ==";
      };
    };
  };
  args = {
    name = "devcontainer-global";
    packageName = "devcontainer-global";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@devcontainers/cli-0.55.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
